import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import {Button} from "@chakra-ui/button";
export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Homepage</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.title}>Applicazione per Gestione turni</h1>

            <Link href="/turni">
                <Button>Turni</Button>
            </Link>
        </div>
    );
}
